---
title: "Spatial Analysis and Statistical Modeling with R and spmodel"
subtitle: "2024 Society for Freshwater Science Conference"
date: June 02, 2024
format:
  revealjs:
    author: 
      - "Michael Dumelle"
      - "Ryan Hill"
    institute: 
      - "EPA (USA)"
      - "EPA (USA)"
    slide-number: true
    preview-links: true
    transition: fade
    theme: [default, slides.scss]
    smaller: false
    auto-stretch: true
    code-link: true
    incremental: false
execute: 
  echo: true
embed-resources: true
bibliography: references.bib
---

```{r}
#| label: setup
#| include: false

# set width of code output
options(width = 80)

# load background packages
library(countdown)
```

## Welcome!

1. Please visit [https://usepa.github.io/spatial.sfs2024/](https://usepa.github.io/spatial.sfs2024/) to view the workshop's accompanying workbook

2. If necessary, install and load R packages by visiting "Setup" in the workbook's "Welcome" section 

3. (Optional) Download the workshop slides (instructions in the workbook's "Welcome" section)

4. Follow along and have fun!

## Who Are We?

__Michael Dumelle__ (he/him/his) is a statistician for the United States Environmental Protection Agency (USEPA). He works primarily on facilitating the survey design and analysis of USEPA’s National Aquatic Resource Surveys (NARS), which characterize the condition of waters across the United States. His primary research interests are in spatial statistics, survey design, environmental and ecological applications, and software development.

## Who Are We?

__Ryan Hill__ (he/him/his) is an aquatic ecologist with the U.S. EPA Office of Research and Development. He is interested in how watershed conditions drive differences in freshwater diversity and water quality across the United States. He has worked extensively with federal physical, chemical, and biological datasets to gain insights into the factors affecting water quality and biotic condition of freshwaters across the conterminous US. He has also worked to develop and distribute large datasets of geospatial watershed metrics of streams and lakes for the Agency (EPA’s StreamCat and LakeCat datasets). 

## Who Are We?

__Lara Jansen__ (she/her/hers) is an aquatic community ecologist and an ORISE postdoctoral fellow working on predictive models of benthic macroinvertebrate communities across the conterminous US in relation to watershed factors. Lara completed her PhD in Environmental Science at Portland State University in 2023, studying the drivers and dynamics of harmful algal blooms in mountain lakes with Dr. Angela Strecker.She obtained a MS in Natural Resource Sciences at Cal Poly Humboldt University with a thesis focused on the downstream impacts of dam flow regulation on benthic macroinvertebrate and algal communities. 

## Who Are We?

__Wade Boys__ (he/him/his) is a graduate student at the University of Arkansas broadly interested in understanding how aquatic ectotherms will respond to climate change, especially the role of phenotypic plasticity in adapting to a warming world. Wade is a firm believer that science is not finished until it is communicated. In addition to research, he finds great purpose in cultivating community and connecting science to our everyday experiences as humans.

## Disclaimer

The views expressed in this workshop are those of the authors and do not necessarily represent the views or policies of the U.S. Environmental Protection Agency. Any mention of trade names, products, or services does not imply an endorsement by the U.S. government or the U.S. Environmental Protection Agency. The U.S. Environmental Protection Agency does not endorse any commercial products, services, or enterprises.


## What is `spmodel`?

`spmodel` is an `R` package to fit, summarize, and predict for a variety of spatial statistical models. Some of the things that `spmodel` can do include:

::: incremental
-   Fit spatial linear and generalized linear models for point-referenced and areal (lattice) data
-   Compare model fits and inspect model diagnostics
-   Predict at unobserved spatial locations (i.e., Kriging)
-   And much more!
:::

## Why use `spmodel`?

There are many great spatial modeling packages in `R`. A few reasons to use `spmodel` for spatial analysis are that:

::: incremental
-   `spmodel` syntax is similar to base `R` syntax for functions like `lm()`, `glm()`, `summary()`, and `predict()`, making the transition from fitting non-spatial models to spatial models relatively seamless.
-   There are a wide variety of `spmodel` capabilities that give the user significant control over the specific spatial model being fit.
-   `spmodel` is compatible with other modern `R` packages like `broom` and `sf`.
:::

# Spatial Linear Models in `spmodel`

## Goals

::: goals
1.  Construct and describe the spatial linear model
2.  Fit a spatial linear model using `spmodel`
3.  Make spatial predictions at unobserved locations (i.e., Kriging).
:::

## Construct and Describe the Spatial Linear Model

::: goals
1.  Review the nonspatial linear model with independent random errors.
2.  Explain how the spatial linear model differs from the linear model with independent random errors.
3.  Explain how modeling for point-referenced data with distance-based model covariances differs from modeling for areal data with neighborhood-based model covariances.
:::

## Nonspatial Linear Models

* Nonspatial linear models are incredibly flexible tools that quantify the relationship between a response variable and a set of explanatory variables
    
* Examples of nonspatial linear models: multiple linear regression, analysis of variance (ANOVA), splines, polynomial regression, additive models, and mixed effect models

$$
\begin{split} \text{y} & = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \dots + \beta_k + \epsilon \\
i & = 1, 2, \dots, k
\end{split}
$$

## Nonspatial Linear Models

Generalizing becomes

$$
\begin{split} \text{y}_j & = \beta_0 + \beta_1 x_{1, j} + \beta_2 x_{2, j} + \dots + \beta_k x_{k, j} + \epsilon_j \\
i & = 1, 2, \dots, k \\
j & = 1, 2, \dots, n 
\end{split}
$$ 

## Nonspatial Linear Models

Matrix notation:

$$
\mathbf{y} = \begin{bmatrix}
  \text{y}_1 \\
  \text{y}_2 \\ 
  \vdots \\
  \text{y}_j \\
\end{bmatrix},
\mathbf{X} = 
\begin{bmatrix} 
1 & x_{1, 1} & x_{1, 2} & \dots & x_{1, k} \\
1 & x_{2, 1} & x_{2, 2} & \dots & x_{2, k} \\
\vdots & \vdots & \vdots & \vdots & \vdots \\
1 & x_{n, 1} & x_{n, 2} & \dots & x_{n, k} \\
\end{bmatrix},
$$

## Nonspatial Linear Models

Matrix notation:

$$
\boldsymbol{\beta} =
\begin{bmatrix}
 \beta_0 \\
 \beta_1 \\
 \vdots \\
 \beta_k
\end{bmatrix}, \text{ and }
\boldsymbol{\epsilon} =
\begin{bmatrix}
 \epsilon_0 \\
 \epsilon_1 \\
 \vdots \\
 \epsilon_j
\end{bmatrix},
$$
The nonspatial linear model is written as
$$
\mathbf{y} = \mathbf{X} \boldsymbol{\beta} + \boldsymbol{\epsilon}.
$$

## Acknowledgements

* Thank you so much for attending!
* Questions?
