<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Spatial Analysis and Statistical Modeling with R and spmodel - 2&nbsp; Additional spmodel Features</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./spglm.html" rel="next">
<link href="./splm.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Additional <code>spmodel</code> Features</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Spatial Analysis and Statistical Modeling with R and spmodel</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./splm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Spatial Linear Models in <code>spmodel</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./splm-additional.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Additional <code>spmodel</code> Features</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spglm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Spatial Generalized Linear Models in <code>spmodel</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gis-in-r.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">GIS in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./watershed-delineation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Watershed Delineation in <code>R</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./streamcattools.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">StreamCat &amp; LakeCat</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spatial-glm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Spatial GLM of “Dancer” damselfly (<em>Argia</em>)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#big-spatial-data" id="toc-big-spatial-data" class="nav-link active" data-scroll-target="#big-spatial-data"><span class="toc-section-number">2.1</span>  Big Spatial Data</a>
  <ul>
<li><a href="#model-fitting" id="toc-model-fitting" class="nav-link" data-scroll-target="#model-fitting"><span class="toc-section-number">2.1.1</span>  Model Fitting</a></li>
  <li><a href="#local-prediction" id="toc-local-prediction" class="nav-link" data-scroll-target="#local-prediction"><span class="toc-section-number">2.1.2</span>  Local Prediction</a></li>
  </ul>
</li>
  <li>
<a href="#additional-arguments" id="toc-additional-arguments" class="nav-link" data-scroll-target="#additional-arguments"><span class="toc-section-number">2.2</span>  Additional Arguments</a>
  <ul>
<li><a href="#multiple-models" id="toc-multiple-models" class="nav-link" data-scroll-target="#multiple-models"><span class="toc-section-number">2.2.1</span>  Multiple Models</a></li>
  <li><a href="#non-spatial-random-effects" id="toc-non-spatial-random-effects" class="nav-link" data-scroll-target="#non-spatial-random-effects"><span class="toc-section-number">2.2.2</span>  Non-Spatial Random Effects</a></li>
  <li><a href="#anisotropy" id="toc-anisotropy" class="nav-link" data-scroll-target="#anisotropy"><span class="toc-section-number">2.2.3</span>  Anisotropy</a></li>
  <li><a href="#partition-factors" id="toc-partition-factors" class="nav-link" data-scroll-target="#partition-factors"><span class="toc-section-number">2.2.4</span>  Partition Factors</a></li>
  <li><a href="#fixing-covariance-parameters" id="toc-fixing-covariance-parameters" class="nav-link" data-scroll-target="#fixing-covariance-parameters"><span class="toc-section-number">2.2.5</span>  Fixing Covariance Parameters</a></li>
  <li><a href="#random-forest-spatial-residual-models" id="toc-random-forest-spatial-residual-models" class="nav-link" data-scroll-target="#random-forest-spatial-residual-models"><span class="toc-section-number">2.2.6</span>  Random Forest Spatial Residual Models</a></li>
  </ul>
</li>
  <li>
<a href="#areal-data" id="toc-areal-data" class="nav-link" data-scroll-target="#areal-data"><span class="toc-section-number">2.3</span>  Areal Data</a>
  <ul>
<li><a href="#data-introduction" id="toc-data-introduction" class="nav-link" data-scroll-target="#data-introduction"><span class="toc-section-number">2.3.1</span>  Data Introduction</a></li>
  <li><a href="#spautor-syntax-and-output-interpretation" id="toc-spautor-syntax-and-output-interpretation" class="nav-link" data-scroll-target="#spautor-syntax-and-output-interpretation"><span class="toc-section-number">2.3.2</span>  <code>spautor()</code> Syntax and Output Interpretation</a></li>
  <li><a href="#additional-analysis" id="toc-additional-analysis" class="nav-link" data-scroll-target="#additional-analysis"><span class="toc-section-number">2.3.3</span>  Additional Analysis</a></li>
  <li><a href="#prediction-with-areal-data" id="toc-prediction-with-areal-data" class="nav-link" data-scroll-target="#prediction-with-areal-data"><span class="toc-section-number">2.3.4</span>  Prediction with Areal Data</a></li>
  </ul>
</li>
  <li><a href="#sec-simulate-gauss" id="toc-sec-simulate-gauss" class="nav-link" data-scroll-target="#sec-simulate-gauss"><span class="toc-section-number">2.4</span>  Simulating Spatial Gaussian Data</a></li>
  <li><a href="#r-code-appendix" id="toc-r-code-appendix" class="nav-link" data-scroll-target="#r-code-appendix"><span class="toc-section-number">2.5</span>  R Code Appendix</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-features" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Additional <code>spmodel</code> Features</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><div class="cell">

</div>
<p>Throughout this section, we will use both the <code>spmodel</code> package and the <code>ggplot2</code> package:</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://usepa.github.io/spmodel/">spmodel</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will continue to use the <code>moss</code> data throughout this section.</p>
<p><strong>Goals</strong>:</p>
<ul>
<li>Accommodate big spatial data:
<ul>
<li>Use the <code>local</code> argument in <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> to fit a spatial linear model to a large data set.</li>
<li>Use the <code>local</code> argument in <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> (or <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code>) to make predictions for a large data set.</li>
</ul>
</li>
<li>Incorporate additional arguments to <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> (and later, <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code>) to:
<ul>
<li>Fit and predict for multiple models simultaneously.</li>
<li>Fit a spatial linear model with non-spatial random effects.</li>
<li>Fit a spatial linear model with anisotropy.</li>
<li>Fit a spatial linear model with a partition factor.</li>
<li>Fix certain spatial covariance parameters at known values.</li>
<li>Fit a random forest spatial residual linear model and make predictions.</li>
</ul>
</li>
<li>Use the <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code> function in <code>spmodel</code> to fit a spatial linear model to areal data:
<ul>
<li>Connect parameter estimates in the summary output of <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code> to the spatial linear model introduced in <a href="splm.html#eq-splm">Equation&nbsp;<span>1.4</span></a> in <a href="splm.html"><span>Chapter&nbsp;1</span></a>.</li>
<li>Apply some of the other functions introduced in <a href="splm.html"><span>Chapter&nbsp;1</span></a> to a model object fit with <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code>.</li>
</ul>
</li>
<li>Simulate spatial Gaussian data using <code><a href="https://usepa.github.io/spmodel/reference/sprnorm.html">sprnorm()</a></code>.</li>
</ul>
<section id="big-spatial-data" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="big-spatial-data">
<span class="header-section-number">2.1</span> Big Spatial Data</h2>
<p>For large observed data sets, fitting spatial linear models or making predictions is challenging because these operations require a covariance matrix inverse, which are computationally challenging to obtain. Typically, observed data samples sizes approaching around 10,000 make model fitting or prediction infeasible on a standard computer in a reasonable amount of time (your definition of this may vary). This necessitates the use of model fitting and prediction tools that work for large data sets. <code>spmodel</code> offers big data methods for model fitting and prediction for point-referenced data via the <code>local</code> argument to <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> and <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code>.</p>
<section id="model-fitting" class="level3" data-number="2.1.1"><h3 data-number="2.1.1" class="anchored" data-anchor-id="model-fitting">
<span class="header-section-number">2.1.1</span> Model Fitting</h3>
<p><code>spmodel</code> implements “local” spatial indexing as described by <span class="citation" data-cites="hoef2023indexing">Ver Hoef et al. (<a href="references.html#ref-hoef2023indexing" role="doc-biblioref">2023</a>)</span>. Observations are first assigned an index. Then for the purposes of model fitting, observations with different indexes are assumed uncorrelated. Assuming observations with different indexes are uncorrelated induces sparsity in the covariance matrix, which greatly reduces the computational time required for operations that involve its inverse. Models fit using spatial indexing are capable of fitting models with hundreds of thousands of observations relatively quickly. <span class="citation" data-cites="hoef2023indexing">Ver Hoef et al. (<a href="references.html#ref-hoef2023indexing" role="doc-biblioref">2023</a>)</span> showed that in a variety of scenarios, spatial indexing yielded fixed effect confidence intervals with proper coverage.</p>
<p>To illustrate spatial indexing in <code>spmodel</code>, we first simulate a response variable <code>sim_response</code> with <code>5000</code> observations at random spatial locations in the unit square (<code>sim_coords</code>). Then we place the response and coordinates in a <code>data.frame</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">06022024</span><span class="op">)</span></span>
<span><span class="va">sim_params</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spcov_params.html">spcov_params</a></span><span class="op">(</span><span class="st">"exponential"</span>, de <span class="op">=</span> <span class="fl">7</span>, ie <span class="op">=</span> <span class="fl">2</span>, range <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">5000</span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span></span>
<span><span class="va">sim_coords</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span><span class="op">)</span></span>
<span></span>
<span><span class="va">sim_response</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/sprnorm.html">sprnorm</a></span><span class="op">(</span><span class="va">sim_params</span>, data <span class="op">=</span> <span class="va">sim_coords</span>, xcoord <span class="op">=</span> <span class="va">x</span>, ycoord <span class="op">=</span> <span class="va">y</span><span class="op">)</span></span>
<span><span class="va">sim_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">sim_coords</span>, <span class="va">sim_response</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We visualize the data by running</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">sim_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span>, color <span class="op">=</span> <span class="va">sim_response</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_color_viridis_c</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">8</span>, <span class="fl">9</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_gray</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-simdata" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="splm-additional_files/figure-html/fig-simdata-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2.1: Distribution of simulated data</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We provide more detail regarding using <code>spmodel</code> to simulate data later on in this section.</p>
</div>
</div>
<p>We then use <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> to fit a spatial model to <code>sim_data</code>, providing the <code>xcoord</code> and <code>ycoord</code> arguments because <code>sim_data</code> is a <code>data.frame</code>, not an <code>sf</code> object. To implement spatial indexing, we use the <code>local</code> argument to <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code>. Setting <code>local</code> to <code>TRUE</code> chooses default spatial indexing settings. We fit the model and time it by running</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_start_time</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/proc.time.html">proc.time</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">bdmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">sim_response</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">sim_data</span>,</span>
<span>     spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>     xcoord <span class="op">=</span> <span class="va">x</span>, ycoord <span class="op">=</span> <span class="va">y</span>,</span>
<span>     local <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">fit_end_time</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/proc.time.html">proc.time</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">fit_end_time</span> <span class="op">-</span> <span class="va">fit_start_time</span></span>
<span><span class="co">#&gt;    user  system elapsed </span></span>
<span><span class="co">#&gt;    6.86    0.93   10.88</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The model with <code>5000</code> observations is fit in just 10.88 seconds.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>When the sample size is larger than 5000 observations, <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> implements spatial indexing by default, as fitting time without spatial indexing becomes lengthy. This behavior can be overridden by explicitly setting <code>local</code> to <code>FALSE</code>.</p>
</div>
</div>
<p>A summary of the model fit yields</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">bdmod</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; splm(formula = sim_response ~ 1, data = sim_data, spcov_type = "exponential", </span></span>
<span><span class="co">#&gt;     xcoord = x, ycoord = y, local = TRUE)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span><span class="co">#&gt; -8.4301 -1.8626  0.1926  1.8081  7.9181 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (fixed):</span></span>
<span><span class="co">#&gt;             Estimate Std. Error z value Pr(&gt;|z|)</span></span>
<span><span class="co">#&gt; (Intercept)   0.5384     1.2610   0.427    0.669</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (exponential spatial covariance):</span></span>
<span><span class="co">#&gt;     de     ie  range </span></span>
<span><span class="co">#&gt; 4.3557 1.9964 0.4643</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The other way to specify <code>local</code> in <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> is via a list object, which offers much more control and customization over the spatial indexing. To learn more, read about <code>local</code> in <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code>’s help page by running <code><a href="https://usepa.github.io/spmodel/reference/splm.html">?splm</a></code>.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Even for two separate data sets with the same sample size fit on the same machine, the computational time required to fit models via spatial indexing varies, depending on many factors like the number of iterations required for convergence and the number of observations assigned to each spatial index.</p>
</div>
</div>
</section><section id="local-prediction" class="level3" data-number="2.1.2"><h3 data-number="2.1.2" class="anchored" data-anchor-id="local-prediction">
<span class="header-section-number">2.1.2</span> Local Prediction</h3>
<p>Using the fitted model, <span class="citation" data-cites="hoef2023indexing">Ver Hoef et al. (<a href="references.html#ref-hoef2023indexing" role="doc-biblioref">2023</a>)</span> evaluates the performance of local neighborhood prediction. Local neighborhood prediction only uses some of the observed data to predict for an unobserved location of interest. Local neighborhood prediction is capable of making predictions of hundreds of thousands of observations relatively quickly. <span class="citation" data-cites="hoef2023indexing">Ver Hoef et al. (<a href="references.html#ref-hoef2023indexing" role="doc-biblioref">2023</a>)</span> showed that in a variety of scenarios, local neighborhood prediction yielded prediction intervals with proper coverage.</p>
<p>To illustrate local neighborhood prediction in <code>spmodel</code>, we first simulate <code>3000</code> new random spatial locations in the unit square (<code>sim_coords</code>). Then we place the coordinates in a <code>data.frame</code> and visualize:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">n_pred</span> <span class="op">&lt;-</span> <span class="fl">3000</span></span>
<span><span class="va">x_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">n_pred</span><span class="op">)</span></span>
<span><span class="va">y_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">n_pred</span><span class="op">)</span></span>
<span><span class="va">sim_preds</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x_pred</span>, y <span class="op">=</span> <span class="va">y_pred</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To implement local neighborhood prediction, we use the <code>local</code> argument to <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> (or <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code>). Setting <code>local</code> in <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> (or <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code>) to <code>TRUE</code> chooses default local neighborhood prediction settings. We compute local neighborhood predictions at the unobserved locations in <code>sim_preds</code> and time it by running</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pred_start_time</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/proc.time.html">proc.time</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">sim_preds</span><span class="op">$</span><span class="va">preds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">bdmod</span>, newdata <span class="op">=</span> <span class="va">sim_preds</span>, local <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">pred_end_time</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/proc.time.html">proc.time</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">pred_end_time</span> <span class="op">-</span> <span class="va">pred_start_time</span></span>
<span><span class="co">#&gt;    user  system elapsed </span></span>
<span><span class="co">#&gt;   20.42    1.35   28.65</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>3000</code> predictions are computed in just 28.65 seconds. We visualize them by running</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">sim_preds</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span>, color <span class="op">=</span> <span class="va">preds</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_color_viridis_c</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">8</span>, <span class="fl">9</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_gray</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-simpreds" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="splm-additional_files/figure-html/fig-simpreds-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2.2: Distribution of local neighborhood predictions using the model fit to the large simulated data set.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>These predictions at the unobserved locations closely match the pattern of the observed data.</p>
<p>The other way to specify <code>local</code> in <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> (or <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code>) is via a list object, which offers much more control and customization over the local neighborhood prediction. To learn more, read about <code>local</code> in <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code>’s (or <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code>’s) help page by running <code><a href="https://usepa.github.io/spmodel/reference/predict.spmodel.html">?predict.spmodel</a></code> (or <code><a href="https://usepa.github.io/spmodel/reference/augment.spmodel.html">?augment.spmodel</a></code>).</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Most of the computational burden associated with prediction is actually from the observed data sample size used to fit the model (because an inverse is needed). As long as the observed data sample sizes are a few thousand or fewer, local prediction is not imperative, no matter the size of the prediction data. Note that parallel process can be used whether or not local prediction is implemented.</p>
</div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><code><a href="https://usepa.github.io/spmodel/reference/loocv.html">loocv()</a></code> also has a <code>local</code> argument for large data sets that is structured the same as <code>local</code> for <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> (and <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code>).</p>
</div>
</div>
</section></section><section id="additional-arguments" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="additional-arguments">
<span class="header-section-number">2.2</span> Additional Arguments</h2>
<section id="multiple-models" class="level3" data-number="2.2.1"><h3 data-number="2.2.1" class="anchored" data-anchor-id="multiple-models">
<span class="header-section-number">2.2.1</span> Multiple Models</h3>
<p><code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> fits multiple models simultaneously when <code>spcov_type</code> is a vector with more than one element:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">spmods</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>, data <span class="op">=</span> <span class="va">moss</span>,</span>
<span>              spcov_type <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"exponential"</span>, <span class="st">"gaussian"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>spmods</code> is a list with two elements: <code>exponential</code>, using the exponential spatial covariance; and <code>gaussian</code>, using the Gaussian spatial covariance.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">spmods</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "exponential" "gaussian"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>spmods</code> is natural to combine with <code><a href="https://usepa.github.io/spmodel/reference/glances.html">glances()</a></code> to glance at each model fit:</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://usepa.github.io/spmodel/reference/glances.html">glances</a></span><span class="op">(</span><span class="va">spmods</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 10</span></span>
<span><span class="co">#&gt;   model      n     p  npar value   AIC  AICc logLik deviance pseudo.r.squared</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 expon…   365     2     3  367.  373.  373.  -184.     363.            0.683</span></span>
<span><span class="co">#&gt; 2 gauss…   365     2     3  435.  441.  441.  -218.     363.            0.686</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and to combine with <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> to predict for each model fit.</p>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Work with a neighbor to find 90% confidence intervals for the fixed effects in the Gaussian model using either (1) <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> or (2) <code><a href="https://rdrr.io/r/stats/confint.html">confint()</a></code>. Before beginning, decide with your neighbor who will begin working on (1) <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> and who will begin working on (2) <code><a href="https://rdrr.io/r/stats/confint.html">confint()</a></code>.</p>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">spmods</span><span class="op">$</span><span class="va">gaussian</span>, conf.int <span class="op">=</span> <span class="cn">TRUE</span>, conf.level <span class="op">=</span> <span class="fl">0.90</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 7</span></span>
<span><span class="co">#&gt;   term          estimate std.error statistic p.value conf.low conf.high</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 (Intercept)      9.21     0.196       46.9       0    8.89      9.53 </span></span>
<span><span class="co">#&gt; 2 log_dist2road   -0.519    0.0184     -28.2       0   -0.549    -0.489</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">spmods</span><span class="op">$</span><span class="va">gaussian</span>, level <span class="op">=</span> <span class="fl">0.90</span><span class="op">)</span></span>
<span><span class="co">#&gt;                      5 %       95 %</span></span>
<span><span class="co">#&gt; (Intercept)    8.8853387  9.5310288</span></span>
<span><span class="co">#&gt; log_dist2road -0.5493091 -0.4887111</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="non-spatial-random-effects" class="level3" data-number="2.2.2"><h3 data-number="2.2.2" class="anchored" data-anchor-id="non-spatial-random-effects">
<span class="header-section-number">2.2.2</span> Non-Spatial Random Effects</h3>
<p>In the <code>moss</code> data, there are actually some spatial locations that have more than one measurement due to multiple samples being collected at a single location or due to a single sample being tested multiple times in the laboratory. The <code>sample</code> variable indexes the spatial location:</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">moss</span></span>
<span><span class="co">#&gt; Simple feature collection with 365 features and 7 fields</span></span>
<span><span class="co">#&gt; Geometry type: POINT</span></span>
<span><span class="co">#&gt; Dimension:     XY</span></span>
<span><span class="co">#&gt; Bounding box:  xmin: -445884.1 ymin: 1929616 xmax: -383656.8 ymax: 2061414</span></span>
<span><span class="co">#&gt; Projected CRS: NAD83 / Alaska Albers</span></span>
<span><span class="co">#&gt; # A tibble: 365 × 8</span></span>
<span><span class="co">#&gt;    sample field_dup lab_rep year  sideroad log_dist2road log_Zn</span></span>
<span><span class="co">#&gt;    &lt;fct&gt;  &lt;fct&gt;     &lt;fct&gt;   &lt;fct&gt; &lt;fct&gt;            &lt;dbl&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt;  1 001PR  1         1       2001  N                 2.68   7.33</span></span>
<span><span class="co">#&gt;  2 001PR  1         2       2001  N                 2.68   7.38</span></span>
<span><span class="co">#&gt;  3 002PR  1         1       2001  N                 2.54   7.58</span></span>
<span><span class="co">#&gt;  4 003PR  1         1       2001  N                 2.97   7.63</span></span>
<span><span class="co">#&gt;  5 004PR  1         1       2001  N                 2.72   7.26</span></span>
<span><span class="co">#&gt;  6 005PR  1         1       2001  N                 2.76   7.65</span></span>
<span><span class="co">#&gt;  7 006PR  1         1       2001  S                 2.30   7.59</span></span>
<span><span class="co">#&gt;  8 007PR  1         1       2001  N                 2.78   7.16</span></span>
<span><span class="co">#&gt;  9 008PR  1         1       2001  N                 2.93   7.19</span></span>
<span><span class="co">#&gt; 10 009PR  1         1       2001  N                 2.79   8.07</span></span>
<span><span class="co">#&gt; # ℹ 355 more rows</span></span>
<span><span class="co">#&gt; # ℹ 1 more variable: geometry &lt;POINT [m]&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We might expect Zinc concentration to be correlated within a spatial location; therefore, we might want to add <code>sample</code> as a non-spatial random effect (here, an intercept random effect) to the model with <code>log_Zn</code> as the response and <code>log_dist2road</code> as the predictor. The <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> function allows non-spatial random effects to be incorporated with the <code>random</code> argument, which takes a formula specification that is similar in syntax as the <code>nlme</code> <span class="citation" data-cites="pinheiro2006mixed">(<a href="references.html#ref-pinheiro2006mixed" role="doc-biblioref">Pinheiro and Bates 2006</a>)</span> and <code>lme4</code> <span class="citation" data-cites="bates2015lme4">(<a href="references.html#ref-bates2015lme4" role="doc-biblioref">Bates et al. 2015</a>)</span> packages.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">randint</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>                data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>                random <span class="op">=</span> <span class="op">~</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">sample</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>For the <code>randint</code> model, in the <code>random</code> argument, <code>sample</code> is shorthand for <code>(1 | sample)</code>. So the <code>randint</code> model could be written more concisely as</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">randint</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>                      data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>                      random <span class="op">=</span> <span class="op">~</span> <span class="va">sample</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>The summary output now shows an estimate of the variance of the random intercepts, in addition to the estimated fixed effects and estimated spatial covariance parameters.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">randint</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; splm(formula = log_Zn ~ log_dist2road, data = moss, spcov_type = "exponential", </span></span>
<span><span class="co">#&gt;     random = ~sample)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span><span class="co">#&gt; -2.6234 -1.3228 -0.8026 -0.2642  1.0998 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (fixed):</span></span>
<span><span class="co">#&gt;               Estimate Std. Error z value Pr(&gt;|z|)    </span></span>
<span><span class="co">#&gt; (Intercept)    9.66066    0.26770   36.09   &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; log_dist2road -0.55028    0.02071  -26.58   &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Pseudo R-squared: 0.6605</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (exponential spatial covariance):</span></span>
<span><span class="co">#&gt;        de        ie     range </span></span>
<span><span class="co">#&gt; 3.153e-01 2.094e-02 1.083e+04 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (random effects):</span></span>
<span><span class="co">#&gt; 1 | sample </span></span>
<span><span class="co">#&gt;    0.07995</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And, <code><a href="https://usepa.github.io/spmodel/reference/glances.html">glances()</a></code> shows that the model with the random intercepts is a better fit to the data than the model without random intercepts.</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">spmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>              data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://usepa.github.io/spmodel/reference/glances.html">glances</a></span><span class="op">(</span><span class="va">spmod</span>, <span class="va">randint</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 10</span></span>
<span><span class="co">#&gt;   model      n     p  npar value   AIC  AICc logLik deviance pseudo.r.squared</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 randi…   365     2     4  335.  343.  343.  -168.     363.            0.661</span></span>
<span><span class="co">#&gt; 2 spmod    365     2     3  367.  373.  373.  -184.     363.            0.683</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As another example, we might consider a model that also has random intercepts for <code>year</code>, or, a model that also has both random intercepts for <code>year</code> and random slopes for <code>log_dist2road</code> within <code>year</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">yearint</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>                      data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>                      random <span class="op">=</span> <span class="op">~</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">sample</span> <span class="op">+</span> <span class="va">year</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">yearsl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>                      data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>                      random <span class="op">=</span> <span class="op">~</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">sample</span><span class="op">)</span> <span class="op">+</span> </span>
<span>                       <span class="op">(</span><span class="va">log_dist2road</span> <span class="op">|</span> <span class="va">year</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code><a href="https://usepa.github.io/spmodel/reference/glances.html">glances()</a></code> shows that, of these four models, the model that includes random intercepts for <code>sample</code>, random intercepts for <code>year</code>, and random slopes for <code>year</code> is best, according to the AIC and AICc metrics.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://usepa.github.io/spmodel/reference/glances.html">glances</a></span><span class="op">(</span><span class="va">spmod</span>, <span class="va">randint</span>, <span class="va">yearint</span>, <span class="va">yearsl</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 4 × 10</span></span>
<span><span class="co">#&gt;   model      n     p  npar value   AIC  AICc logLik deviance pseudo.r.squared</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 yearsl   365     2     6  190.  202.  202.  -94.9     363.            0.215</span></span>
<span><span class="co">#&gt; 2 yeari…   365     2     4  230.  238.  238. -115.      363.            0.729</span></span>
<span><span class="co">#&gt; 3 randi…   365     2     4  335.  343.  343. -168.      363.            0.661</span></span>
<span><span class="co">#&gt; 4 spmod    365     2     3  367.  373.  373. -184.      363.            0.683</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The syntax <code>~ (log_dist2road | year)</code> specifies that both random intercepts for <code>year</code> and random slopes for <code>log_dist2road</code> within <code>year</code> should be included in the model. If only random slopes are desired, then we should set <code>random</code> to <code>~ (-1 + log_dist2road | year)</code>.</p>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Perhaps a model with random intercepts for <code>sample</code> and random intercepts and slopes for <code>year</code> but without any spatial covariance is an even better fit to the data. Fit such a model by specifying <code>spcov_type</code> to be <code>"none"</code>. Then, use <code><a href="https://usepa.github.io/spmodel/reference/glances.html">glances()</a></code> to see how well this non-spatial model fits the <code>moss</code> data compared to the spatially explicit models.</p>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nospcov</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>                    data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"none"</span>,</span>
<span>                    random <span class="op">=</span> <span class="op">~</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">sample</span><span class="op">)</span> <span class="op">+</span> </span>
<span>                      <span class="op">(</span><span class="va">log_dist2road</span> <span class="op">|</span> <span class="va">year</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://usepa.github.io/spmodel/reference/glances.html">glances</a></span><span class="op">(</span><span class="va">spmod</span>, <span class="va">randint</span>, <span class="va">yearint</span>, <span class="va">yearsl</span>, <span class="va">nospcov</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 10</span></span>
<span><span class="co">#&gt;   model      n     p  npar value   AIC  AICc logLik deviance pseudo.r.squared</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 yearsl   365     2     6  190.  202.  202.  -94.9     363.            0.215</span></span>
<span><span class="co">#&gt; 2 yeari…   365     2     4  230.  238.  238. -115.      363.            0.729</span></span>
<span><span class="co">#&gt; 3 randi…   365     2     4  335.  343.  343. -168.      363.            0.661</span></span>
<span><span class="co">#&gt; 4 spmod    365     2     3  367.  373.  373. -184.      363.            0.683</span></span>
<span><span class="co">#&gt; 5 nospc…   365     2     4  456.  464.  464. -228.      363             0.119</span></span>
<span><span class="co">## the model with no explicit spatial covariance has the worst fit </span></span>
<span><span class="co">## of the five models.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="anisotropy" class="level3" data-number="2.2.3"><h3 data-number="2.2.3" class="anchored" data-anchor-id="anisotropy">
<span class="header-section-number">2.2.3</span> Anisotropy</h3>
<p>By default, <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> uses isotropic spatial covariance. Spatial covariance is isotropic if it behaves similarly in all directions. A spatial covariance is (geometrically) anisotropic if it does not behave similarly in all directions. Anisotropic models require estimation of two additional parameters: <code>rotate</code> and <code>scale</code>, which control the behavior of the spatial covariance as a function of distance and direction.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">aniso</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>              data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>              anisotropy <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">aniso</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; splm(formula = log_Zn ~ log_dist2road, data = moss, spcov_type = "exponential", </span></span>
<span><span class="co">#&gt;     anisotropy = TRUE)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (fixed):</span></span>
<span><span class="co">#&gt;   (Intercept)  log_dist2road  </span></span>
<span><span class="co">#&gt;         9.548         -0.546  </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (exponential spatial covariance):</span></span>
<span><span class="co">#&gt;        de         ie      range     rotate      scale  </span></span>
<span><span class="co">#&gt; 3.561e-01  6.812e-02  8.732e+03  2.435e+00  4.753e-01</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can again use glances to compare the model that allows for anisotropy with the isotropic model:</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://usepa.github.io/spmodel/reference/glances.html">glances</a></span><span class="op">(</span><span class="va">spmod</span>, <span class="va">aniso</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 10</span></span>
<span><span class="co">#&gt;   model     n     p  npar value   AIC  AICc logLik deviance pseudo.r.squared</span></span>
<span><span class="co">#&gt;   &lt;chr&gt; &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 aniso   365     2     5  362.  372.  372.  -181.     363             0.705</span></span>
<span><span class="co">#&gt; 2 spmod   365     2     3  367.  373.  373.  -184.     363.            0.683</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The anisotropic model does have lower AIC and AICc than the isotropic model, indicating a better fit. However, the reduction in AIC and AICc is quite small, so we may still prefer the isotropic model for simplicity and interpretability.</p>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Visualize the anisotropic level curve for <code>aniso</code> using <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code>. Hint: Run <code><a href="https://usepa.github.io/spmodel/reference/plot.spmodel.html">?plot.spmodel</a></code> or visit <a href="https://usepa.github.io/spmodel/reference/plot.spmodel.html">this link</a>. Which direction does the model predict two responses will be more correlated?</p>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">aniso</span>, which <span class="op">=</span> <span class="fl">8</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="splm-additional_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A clockwise rotation of this level curve by <code>rotate</code> followed by a scaling of the minor axis by the reciprocal of <code>scale</code> yields a spatial covariance that is isotropic.</p>
</div>
</div>
</div>
</section><section id="partition-factors" class="level3" data-number="2.2.4"><h3 data-number="2.2.4" class="anchored" data-anchor-id="partition-factors">
<span class="header-section-number">2.2.4</span> Partition Factors</h3>
<p>A partition factor is a categorical (or factor) variable that forces observations in different levels of the partition factor to be uncorrelated. The <code>year</code> variable in <code>moss</code> has two levels, <code>2001</code> and <code>2006</code>, which correspond to the year of measurement. Suppose the goal is to fit a model that assumes observations from the same year are spatially correlated but observations from different years are not spatially correlated. In this context, <code>year</code> is a partition factor. We fit this model by running</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">part</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>             data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>             partition_factor <span class="op">=</span> <span class="op">~</span> <span class="va">year</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Like the <code>formula</code> and <code>random</code> arguments, the <code>partition_factor</code> argument requires a formula object.</p>
</section><section id="fixing-covariance-parameters" class="level3" data-number="2.2.5"><h3 data-number="2.2.5" class="anchored" data-anchor-id="fixing-covariance-parameters">
<span class="header-section-number">2.2.5</span> Fixing Covariance Parameters</h3>
<p>By default, <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> estimates all unknown covariance parameters. However, we can also fix covariance parameters at known values with the <code>spcov_initial</code> argument for spatial covariance parameters and with the <code>randcov_initial</code> argument for non-spatial covariance parameters.</p>
<p>As an example, suppose that we want to fit a <code>"spherical"</code> covariance model to the moss data, but that, we want to fix the <code>range</code> at <code>20000</code> units so that errors from spatial locations more than 20000 units apart are not spatially correlated. We first create an <code>spcov_initial</code> object with the <code><a href="https://usepa.github.io/spmodel/reference/spcov_initial.html">spcov_initial()</a></code> function:</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">init_spher</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spcov_initial.html">spcov_initial</a></span><span class="op">(</span><span class="st">"spherical"</span>, range <span class="op">=</span> <span class="fl">20000</span>, known <span class="op">=</span> <span class="st">"range"</span><span class="op">)</span></span>
<span><span class="va">init_spher</span></span>
<span><span class="co">#&gt; $initial</span></span>
<span><span class="co">#&gt; range </span></span>
<span><span class="co">#&gt; 20000 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $is_known</span></span>
<span><span class="co">#&gt; range </span></span>
<span><span class="co">#&gt;  TRUE </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attr(,"class")</span></span>
<span><span class="co">#&gt; [1] "spherical"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Within the function call, we specify that, for a <code>"spherical"</code> covariance, we would like to set the <code>range</code> parameter to <code>20000</code> and for that value to be known and therefore fixed in any subsequent estimation. We then provide <code>init_spher</code> as an argument to <code>spcov_initial</code> in <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>, data <span class="op">=</span> <span class="va">moss</span>,</span>
<span>     spcov_initial <span class="op">=</span> <span class="va">init_spher</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; splm(formula = log_Zn ~ log_dist2road, data = moss, spcov_initial = init_spher)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (fixed):</span></span>
<span><span class="co">#&gt;   (Intercept)  log_dist2road  </span></span>
<span><span class="co">#&gt;        9.7194        -0.5607  </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (spherical spatial covariance):</span></span>
<span><span class="co">#&gt;        de         ie      range  </span></span>
<span><span class="co">#&gt; 4.545e-01  8.572e-02  2.000e+04</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When <code>spcov_initial</code> is provided, <code>spcov_type</code> is not a necessary argument to <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code>.</p>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Fit a <code>"spherical"</code> spatial covariance model to the <code>moss</code> data set without a nugget effect (i.e., the model should have the <code>ie</code> independent variance parameter set to <code>0</code> and treated as <code>known</code>). Verify in the summary output that the <code>ie</code> is indeed <code>0</code> for this model.</p>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">init_no_ie</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spcov_initial.html">spcov_initial</a></span><span class="op">(</span><span class="st">"spherical"</span>, ie <span class="op">=</span> <span class="fl">0</span>, known <span class="op">=</span> <span class="st">"ie"</span><span class="op">)</span></span>
<span><span class="va">no_ie</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>, data <span class="op">=</span> <span class="va">moss</span>,</span>
<span>              spcov_initial <span class="op">=</span> <span class="va">init_no_ie</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">no_ie</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; splm(formula = log_Zn ~ log_dist2road, data = moss, spcov_initial = init_no_ie)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span><span class="co">#&gt; -3.1766 -1.8420 -1.2975 -0.7249  0.6577 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (fixed):</span></span>
<span><span class="co">#&gt;               Estimate Std. Error z value Pr(&gt;|z|)    </span></span>
<span><span class="co">#&gt; (Intercept)   10.27912   28.99660   0.354    0.723    </span></span>
<span><span class="co">#&gt; log_dist2road -0.56642    0.01974 -28.693   &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Pseudo R-squared: 0.6967</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (spherical spatial covariance):</span></span>
<span><span class="co">#&gt;        de        ie     range </span></span>
<span><span class="co">#&gt; 8.433e+02 0.000e+00 3.699e+07</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="random-forest-spatial-residual-models" class="level3" data-number="2.2.6"><h3 data-number="2.2.6" class="anchored" data-anchor-id="random-forest-spatial-residual-models">
<span class="header-section-number">2.2.6</span> Random Forest Spatial Residual Models</h3>
<p>Random forests are a popular machine-learning modeling tool. The random forest spatial residual model available in <code>spmodel</code> combines random forest modeling and spatial linear models. First, the model is fit using random forests and fitted values are obtained. Then the response residuals are used to fit a spatial linear model. Predictions at unobserved locations are computed as the sum of the random forest prediction and the predicted (i.e., Kriged) response residual from the spatial linear model. Suppose we split the <code>moss</code> data into training and test data sets, with the goal of predicting <code>log_Zn</code> in the test data.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">NROW</a></span><span class="op">(</span><span class="va">moss</span><span class="op">)</span></span>
<span><span class="va">n_train</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">0.75</span> <span class="op">*</span> <span class="va">n</span><span class="op">)</span></span>
<span><span class="va">n_test</span> <span class="op">&lt;-</span> <span class="va">n</span> <span class="op">-</span> <span class="va">n_train</span></span>
<span><span class="va">train_index</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">n</span>, size <span class="op">=</span> <span class="va">n_train</span><span class="op">)</span></span>
<span><span class="va">moss_train</span> <span class="op">&lt;-</span> <span class="va">moss</span><span class="op">[</span><span class="va">train_index</span>, , <span class="op">]</span></span>
<span><span class="va">moss_test</span> <span class="op">&lt;-</span> <span class="va">moss</span><span class="op">[</span><span class="op">-</span><span class="va">train_index</span>, , <span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We fit a random forest spatial residual model to the test data by running</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">rfsrmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splmRF.html">splmRF</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>, <span class="va">moss_train</span>,</span>
<span>                  spcov_type <span class="op">=</span> <span class="st">"exponential"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We make predictions for the test data by running</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># results omitted</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">rfsrmod</span>, <span class="va">moss_test</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> to store the random forest spatial residual predictions of <code>log_Zn</code> at locations in the test data and then compute the mean-squared prediction error (MSPE). Compare this MSPE to the MSPE from fitting a spatial linear model with an exponential covariance function.</p>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">rf_preds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">rfsrmod</span>, newdata <span class="op">=</span> <span class="va">moss_test</span><span class="op">)</span></span>
<span><span class="va">rf_errors</span> <span class="op">&lt;-</span> <span class="va">moss_test</span><span class="op">$</span><span class="va">log_Zn</span> <span class="op">-</span> <span class="va">rf_preds</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">rf_errors</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.1849228</span></span>
<span></span>
<span><span class="va">splmmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>, <span class="va">moss_train</span>,</span>
<span>                  spcov_type <span class="op">=</span> <span class="st">"exponential"</span><span class="op">)</span></span>
<span><span class="va">splm_preds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">splmmod</span>, newdata <span class="op">=</span> <span class="va">moss_test</span><span class="op">)</span></span>
<span><span class="va">splm_errors</span> <span class="op">&lt;-</span> <span class="va">moss_test</span><span class="op">$</span><span class="va">log_Zn</span> <span class="op">-</span> <span class="va">splm_preds</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">splm_errors</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.1514774</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For these data, the spatial linear model yielded more accurate predictions (lower MSPE).</p>
</div>
</div>
</div>
</section></section><section id="areal-data" class="level2" data-number="2.3"><h2 data-number="2.3" class="anchored" data-anchor-id="areal-data">
<span class="header-section-number">2.3</span> Areal Data</h2>
<section id="data-introduction" class="level3" data-number="2.3.1"><h3 data-number="2.3.1" class="anchored" data-anchor-id="data-introduction">
<span class="header-section-number">2.3.1</span> Data Introduction</h3>
<p>Throughout the section, we will use the <code>seal</code> data in the <code>spmodel</code> package. The <code>seal</code> data is an <code>sf</code> object with a <code>POLYGON</code> geometry. There are 62 polygons in the data, some of which have non-missing values of <code>log_trend</code>, which is the log of the estimated harbor-seal trends that were calculated from abundance data.</p>
<p>The following code generates a visualization of the <code>seal</code> data: polygons that are grey have a missing value for <code>log_trend</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">seal</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="va">log_trend</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_fill_viridis_c</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="splm-additional_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Our goal is to fit a spatial autoregressive model (<a href="splm.html#eq-splm">Equation&nbsp;<span>1.4</span></a> and <a href="splm.html#eq-Rareal">Equation&nbsp;<span>1.6</span></a>) to the <code>log_trend</code> response variable with the <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code> function. Then, we will use the fitted model to predict the <code>log_trend</code> for sites where <code>log_trend</code> is not recorded.</p>
</section><section id="spautor-syntax-and-output-interpretation" class="level3" data-number="2.3.2"><h3 data-number="2.3.2" class="anchored" data-anchor-id="spautor-syntax-and-output-interpretation">
<span class="header-section-number">2.3.2</span> <code>spautor()</code> Syntax and Output Interpretation</h3>
<p>The syntax for fitting a model to areal data with <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code> is very similar to that used for <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code>. Again, there are generally at least three required arguments:</p>
<ul>
<li>
<code>formula</code>: a formula that describes the relationship between the response variable (<span class="math inline">\(\mathbf{y}\)</span>) and explanatory variables (<span class="math inline">\(\mathbf{X}\)</span>)
<ul>
<li>
<code>formula</code> in <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code> is the same as <code>formula</code> in <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> and <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code>
</li>
</ul>
</li>
<li>
<code>data</code>: a <code>data.frame</code> or <code>sf</code> object that contains the response variable, explanatory variables, and spatial information. Note that if <code>data</code> is a <code>data.frame</code>, then <code>W</code> is an additional required argument to <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code>.</li>
<li>
<code>spcov_type</code>: the spatial covariance type (<code>"car"</code> or <code>"sar"</code>)</li>
</ul>
<p>We can fit a conditional auto-regressive (CAR) model with</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sealmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor</a></span><span class="op">(</span><span class="va">log_trend</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">seal</span>, spcov_type <span class="op">=</span> <span class="st">"car"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; spautor(formula = log_trend ~ 1, data = seal, spcov_type = "car")</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;      Min       1Q   Median       3Q      Max </span></span>
<span><span class="co">#&gt; -0.34455 -0.10417  0.04410  0.07338  0.20475 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (fixed):</span></span>
<span><span class="co">#&gt;             Estimate Std. Error z value Pr(&gt;|z|)   </span></span>
<span><span class="co">#&gt; (Intercept) -0.07090    0.02497  -2.839  0.00452 **</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (car spatial covariance):</span></span>
<span><span class="co">#&gt;      de   range   extra </span></span>
<span><span class="co">#&gt; 0.03252 0.42037 0.02177</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
<p>We can relate some of the components in the summary output to the model in <a href="splm.html#eq-splm">Equation&nbsp;<span>1.4</span></a> and <a href="splm.html#eq-Rareal">Equation&nbsp;<span>1.6</span></a>:</p>
<ul>
<li>the value in the <code>Estimate</code> column of the <code>Coefficients (fixed)</code> table form <span class="math inline">\(\boldsymbol{\hat{\beta}}\)</span>, an estimate of <span class="math inline">\(\boldsymbol{\beta}\)</span>.</li>
<li>the <code>de</code> value of 0.033 in the <code>Coefficients (car spatial covariance)</code> table is <span class="math inline">\(\hat{\sigma}^2_{de}\)</span>, which is an estimate of <span class="math inline">\(\sigma^2_{de}\)</span>, the variance of <span class="math inline">\(\boldsymbol{\tau}\)</span>.</li>
<li>the <code>range</code> value of 0.42 in the <code>Coefficients (car spatial covariance)</code> table is <span class="math inline">\(\hat{\phi}\)</span>, an estimate of <span class="math inline">\(\phi\)</span> in <a href="splm.html#eq-Rareal">Equation&nbsp;<span>1.6</span></a>.</li>
</ul>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>By default, <span class="math inline">\(\sigma^2_{ie}\)</span> is assumed to be <code>0</code> for autoregressive models and hence, <code>ie</code> is omitted from the summary output.</p>
</div>
</div>
<p>Though the weight matrix <span class="math inline">\(\mathbf{W}\)</span> in <a href="splm.html#eq-Rareal">Equation&nbsp;<span>1.6</span></a> used in the model does not appear in the summary output, we can pull the weight matrix from the <code>sealmod</code> object with</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sealmod</span><span class="op">$</span><span class="va">W</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By default, <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code> uses <strong>queen contiguity</strong> to form the weight matrix: observations are “neighbors” if they share at least one boundary (even if that boundary is a single point). Recall that observations are not considered neighbors with themselves. Also by default, <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code> row standardizes the weight matrix so that each of the rows in <span class="math inline">\(\mathbf{W}\)</span> sum to <span class="math inline">\(1\)</span>. Row standardization of the weight matrix is performed by default because doing so results in “nice” properties of the resulting covariance matrix <span class="citation" data-cites="ver2018spatial">(<a href="references.html#ref-ver2018spatial" role="doc-biblioref">Ver Hoef et al. 2018</a>)</span>. The first row of the weight matrix is</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sealmod</span><span class="op">$</span><span class="va">W</span><span class="op">[</span><span class="fl">1</span>, <span class="op">]</span></span>
<span><span class="co">#&gt;  [1] 0.0000000 0.3333333 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000</span></span>
<span><span class="co">#&gt;  [8] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000</span></span>
<span><span class="co">#&gt; [15] 0.0000000 0.3333333 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000</span></span>
<span><span class="co">#&gt; [22] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.3333333</span></span>
<span><span class="co">#&gt; [29] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000</span></span>
<span><span class="co">#&gt; [36] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000</span></span>
<span><span class="co">#&gt; [43] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000</span></span>
<span><span class="co">#&gt; [50] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000</span></span>
<span><span class="co">#&gt; [57] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output indicates that the first observation is neighbors with the second observation, the sixteenth observation, and the twenty-eighth observation.</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">$</span><span class="va">W</span><span class="op">[</span><span class="fl">1</span>, <span class="op">]</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1]  2 16 28</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, if we re-examine <span class="math inline">\(\mathbf{W}\)</span>, we can note that some rows of <span class="math inline">\(\mathbf{W}\)</span> do not have any positive values, indicating that some observations in the data have no neighbors. Looking back on the plot of the data, we see that there are indeed a few “island” sites that do not share a boundary with any other polygons. The errors for these spatial locations are assumed to be uncorrelated with all other random errors, and, they are given a unique variance parameter that is the <code>extra</code> spatial covariance estimate in the summary output of the model.</p>
</section><section id="additional-analysis" class="level3" data-number="2.3.3"><h3 data-number="2.3.3" class="anchored" data-anchor-id="additional-analysis">
<span class="header-section-number">2.3.3</span> Additional Analysis</h3>
<p>Most of the helper functions for models fit with <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> are also useful for models fit with <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code>. Additionally, most of the additional arguments for <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> are also additional arguments for <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code>.</p>
<p>All helper functions available for <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code> model objects are also available for <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code> model objects:</p>
<ul>
<li>
<code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code>, <code><a href="https://generics.r-lib.org/reference/glance.html">glance()</a></code>, and <code><a href="https://usepa.github.io/spmodel/reference/glances.html">glances()</a></code>
</li>
<li>model fit statistics with <code><a href="https://rdrr.io/r/stats/AIC.html">AIC()</a></code>, <code><a href="https://usepa.github.io/spmodel/reference/AIC.spmodel.html">AICc()</a></code> and <code>GR2()</code>
</li>
<li>model diagnostics statistics with <code><a href="https://rdrr.io/r/stats/influence.measures.html">cooks.distance()</a></code>, <code><a href="https://rdrr.io/r/stats/residuals.html">residuals()</a></code>, <code><a href="https://rdrr.io/r/stats/fitted.values.html">fitted()</a></code>, etc.</li>
</ul>
<p><code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code> model objects accommodate all additional arguments previously mentioned except big data sets and anisotropy.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Big data applications are not available because the models are parameterized in terms of their inverse covariance matrix, not the covariance matrix, which makes the “local” approach infeasible. The <code>anisotropy</code> argument is not available for <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code> because the covariance for an autoregressive model is based on the neighborhood structure of the spatial locations, not on distance.</p>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Choose a couple of the helper functions that you would like to explore and apply those functions to the fitted seal model.</p>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/AIC.html">AIC</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] -30.87584</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">)</span></span>
<span><span class="co">#&gt;           2           3           4           5           6           7 </span></span>
<span><span class="co">#&gt; -0.07090121 -0.07090121 -0.07090121 -0.07090121 -0.07090121 -0.07090121 </span></span>
<span><span class="co">#&gt;           8          10          11          12          14          16 </span></span>
<span><span class="co">#&gt; -0.07090121 -0.07090121 -0.07090121 -0.07090121 -0.07090121 -0.07090121 </span></span>
<span><span class="co">#&gt;          17          20          21          22          23          24 </span></span>
<span><span class="co">#&gt; -0.07090121 -0.07090121 -0.07090121 -0.07090121 -0.07090121 -0.07090121 </span></span>
<span><span class="co">#&gt;          25          26          28          29          30          31 </span></span>
<span><span class="co">#&gt; -0.07090121 -0.07090121 -0.07090121 -0.07090121 -0.07090121 -0.07090121 </span></span>
<span><span class="co">#&gt;          33          34          35          37          38          39 </span></span>
<span><span class="co">#&gt; -0.07090121 -0.07090121 -0.07090121 -0.07090121 -0.07090121 -0.07090121 </span></span>
<span><span class="co">#&gt;          41          45          59          60 </span></span>
<span><span class="co">#&gt; -0.07090121 -0.07090121 -0.07090121 -0.07090121</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="prediction-with-areal-data" class="level3" data-number="2.3.4"><h3 data-number="2.3.4" class="anchored" data-anchor-id="prediction-with-areal-data">
<span class="header-section-number">2.3.4</span> Prediction with Areal Data</h3>
<p>Prediction of response values for unobserved polygons with areal data requires that the polygons with missing response values be included in the <code>data</code> argument supplied to <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code>. The reason for this requirement is that exclusion of these polygons changes the underlying neighborhood structure of the data, and, therefore changes the covariance matrix.</p>
<p>For areal data, we can obtain predictions for unobserved polygons using <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> on the fitted model object or <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code> on the fitted model object, specifying the <code>newdata</code> argument to be <code>mod$newdata</code>. Both approaches are given below:</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sealmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor</a></span><span class="op">(</span><span class="va">log_trend</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">seal</span>, spcov_type <span class="op">=</span> <span class="st">"car"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">sealmod</span>, newdata <span class="op">=</span> <span class="va">sealmod</span><span class="op">$</span><span class="va">newdata</span><span class="op">)</span></span>
<span><span class="co">#&gt; Simple feature collection with 28 features and 2 fields</span></span>
<span><span class="co">#&gt; Geometry type: POLYGON</span></span>
<span><span class="co">#&gt; Dimension:     XY</span></span>
<span><span class="co">#&gt; Bounding box:  xmin: 913618.8 ymin: 1007542 xmax: 1115097 ymax: 1132682</span></span>
<span><span class="co">#&gt; Projected CRS: NAD83 / Alaska Albers</span></span>
<span><span class="co">#&gt; # A tibble: 28 × 3</span></span>
<span><span class="co">#&gt;    log_trend  .fitted                                                geometry</span></span>
<span><span class="co">#&gt;  *     &lt;dbl&gt;    &lt;dbl&gt;                                           &lt;POLYGON [m]&gt;</span></span>
<span><span class="co">#&gt;  1        NA -0.115   ((1035002 1054710, 1035002 1054542, 1035002 1053542, 1…</span></span>
<span><span class="co">#&gt;  2        NA -0.00908 ((1043093 1020553, 1043097 1020550, 1043101 1020550, 1…</span></span>
<span><span class="co">#&gt;  3        NA -0.0602  ((1099737 1054310, 1099752 1054262, 1099788 1054278, 1…</span></span>
<span><span class="co">#&gt;  4        NA -0.0359  ((1099002 1036542, 1099134 1036462, 1099139 1036431, 1…</span></span>
<span><span class="co">#&gt;  5        NA -0.0723  ((1076902 1053189, 1076912 1053179, 1076931 1053179, 1…</span></span>
<span><span class="co">#&gt;  6        NA -0.0548  ((1070501 1046969, 1070317 1046598, 1070308 1046542, 1…</span></span>
<span><span class="co">#&gt;  7        NA -0.0976  ((1072995 1054942, 1072996 1054910, 1072997 1054878, 1…</span></span>
<span><span class="co">#&gt;  8        NA -0.0714  ((960001.5 1127667, 960110.8 1127542, 960144.1 1127495…</span></span>
<span><span class="co">#&gt;  9        NA -0.0825  ((1031308 1079817, 1031293 1079754, 1031289 1079741, 1…</span></span>
<span><span class="co">#&gt; 10        NA -0.0592  ((998923.7 1053647, 998922.5 1053609, 998950 1053631, …</span></span>
<span><span class="co">#&gt; # ℹ 18 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>mod$newdata</code> syntax also works for models fit with <code><a href="https://usepa.github.io/spmodel/reference/splm.html">splm()</a></code>, where the <code>data</code> used contains missing values for the response variable at any unobserved locations.</p>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Verify that the fitted autoregressive model with the <code>seal</code> data changes when the polygons with missing response values are excluded from the <code>data</code> argument in <code><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor()</a></code>. The following code creates a data without the polygons with missing values:</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">is_missing</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">seal</span><span class="op">$</span><span class="va">log_trend</span><span class="op">)</span></span>
<span><span class="va">seal_nomiss</span> <span class="op">&lt;-</span> <span class="va">seal</span><span class="op">[</span><span class="op">!</span><span class="va">is_missing</span>, , <span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sealmod_nomiss</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor</a></span><span class="op">(</span><span class="va">log_trend</span> <span class="op">~</span> <span class="fl">1</span>,</span>
<span>                          data <span class="op">=</span> <span class="va">seal_nomiss</span>, spcov_type <span class="op">=</span> <span class="st">"car"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; spautor(formula = log_trend ~ 1, data = seal, spcov_type = "car")</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (fixed):</span></span>
<span><span class="co">#&gt; (Intercept)  </span></span>
<span><span class="co">#&gt;     -0.0709  </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (car spatial covariance):</span></span>
<span><span class="co">#&gt;      de    range    extra  </span></span>
<span><span class="co">#&gt; 0.03252  0.42037  0.02177</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">sealmod_nomiss</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; spautor(formula = log_trend ~ 1, data = seal_nomiss, spcov_type = "car")</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (fixed):</span></span>
<span><span class="co">#&gt; (Intercept)  </span></span>
<span><span class="co">#&gt;    -0.08152  </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients (car spatial covariance):</span></span>
<span><span class="co">#&gt;      de    range    extra  </span></span>
<span><span class="co">#&gt; 0.02297  0.41280  0.01958</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section></section><section id="sec-simulate-gauss" class="level2" data-number="2.4"><h2 data-number="2.4" class="anchored" data-anchor-id="sec-simulate-gauss">
<span class="header-section-number">2.4</span> Simulating Spatial Gaussian Data</h2>
<p>We simulate Gaussian spatial data using <code><a href="https://usepa.github.io/spmodel/reference/sprnorm.html">sprnorm()</a></code>. <code><a href="https://usepa.github.io/spmodel/reference/sprnorm.html">sprnorm()</a></code> is similar in structure to <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code> for simulating non-spatial Gaussian data. The first argument to <code><a href="https://usepa.github.io/spmodel/reference/sprnorm.html">sprnorm()</a></code> is <code>spcov_params</code>, which is a spatial covariance parameter object created with <code><a href="https://usepa.github.io/spmodel/reference/spcov_params.html">spcov_params()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">params</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spcov_params.html">spcov_params</a></span><span class="op">(</span><span class="st">"exponential"</span>, de <span class="op">=</span> <span class="fl">1</span>, ie <span class="op">=</span> <span class="fl">0.5</span>, range <span class="op">=</span> <span class="fl">5e5</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>When the <code>type</code> argument to <code><a href="https://rdrr.io/r/stats/coef.html">coef()</a></code> is <code>"spcov"</code>, the estimated spatial covariance parameters are returned as an <code>spcov_params</code> object, naturally usable simulation-based contexts that require conditioning on these estimated parameters.</p>
</div>
</div>
<p><code><a href="https://usepa.github.io/spmodel/reference/sprnorm.html">sprnorm()</a></code> simulates data at each location in <code>data</code> for each of <code>n</code> samples (specified via <code>n</code>) with some mean vector (specified via <code>mean</code>). We simulate one realization of zero-mean Gaussian data with spatial covariance structure from <code>params</code> at each location in the <code>sulfate</code> data by running</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">sulfate</span><span class="op">$</span><span class="va">z</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/sprnorm.html">sprnorm</a></span><span class="op">(</span><span class="va">params</span>, data <span class="op">=</span> <span class="va">sulfate</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Simulating spatial data in <code>spmodel</code> requires the inverse (more rigorously, the Cholesky decomposition) of the covariance matrix, which can take awhile for sample sizes exceeding 10,000. Regardless of the number of realizations simulated, this inverse is only needed once, which means that simulating many realizations (via <code>samples</code>) takes nearly the same time as simulating just one.</p>
</div>
</div>
<p>We visualize this realization by running</p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">sulfate</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>color <span class="op">=</span> <span class="va">z</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_color_viridis_c</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_gray</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="splm-additional_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We visualize an empirical semivariogram of this realization by running</p>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">esv_out</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/esv.html">esv</a></span><span class="op">(</span><span class="va">z</span> <span class="op">~</span> <span class="fl">1</span>, <span class="va">sulfate</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">esv_out</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">dist</span>, y <span class="op">=</span> <span class="va">gamma</span>, size <span class="op">=</span> <span class="va">np</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/lims.html">lims</a></span><span class="op">(</span>y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="cn">NA</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_gray</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="splm-additional_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The empirical semivariogram is a diagnostic tool that can be used to characterize spatial dependence. On the x-axis is distance between observations. On the y-axis is the average squared difference between response variables (semivariance) in different distance “bins”. Typically when spatial dependence exists, the semivariance is smaller at short distances and larger at far distances. In the figure above, the size of the circle is proportional to the number of unique response variable pairs used in the distance bin. To assess leftover spatial dependence in a model, typically semivariograms are constructed on residuals from the nonspatial fitted model. The empirical semivariogram is intimately connected to empirical correlations/correllograms.</p>
</div>
</div>
</section><section id="r-code-appendix" class="level2" data-number="2.5"><h2 data-number="2.5" class="anchored" data-anchor-id="r-code-appendix">
<span class="header-section-number">2.5</span> R Code Appendix</h2>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://usepa.github.io/spmodel/">spmodel</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">06022024</span><span class="op">)</span></span>
<span><span class="va">sim_params</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spcov_params.html">spcov_params</a></span><span class="op">(</span><span class="st">"exponential"</span>, de <span class="op">=</span> <span class="fl">7</span>, ie <span class="op">=</span> <span class="fl">2</span>, range <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">5000</span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span></span>
<span><span class="va">sim_coords</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span><span class="op">)</span></span>
<span></span>
<span><span class="va">sim_response</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/sprnorm.html">sprnorm</a></span><span class="op">(</span><span class="va">sim_params</span>, data <span class="op">=</span> <span class="va">sim_coords</span>, xcoord <span class="op">=</span> <span class="va">x</span>, ycoord <span class="op">=</span> <span class="va">y</span><span class="op">)</span></span>
<span><span class="va">sim_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">sim_coords</span>, <span class="va">sim_response</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">sim_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span>, color <span class="op">=</span> <span class="va">sim_response</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_color_viridis_c</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">8</span>, <span class="fl">9</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_gray</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span></span>
<span><span class="va">fit_start_time</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/proc.time.html">proc.time</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">bdmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">sim_response</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">sim_data</span>,</span>
<span>     spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>     xcoord <span class="op">=</span> <span class="va">x</span>, ycoord <span class="op">=</span> <span class="va">y</span>,</span>
<span>     local <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">fit_end_time</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/proc.time.html">proc.time</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">fit_end_time</span> <span class="op">-</span> <span class="va">fit_start_time</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">bdmod</span><span class="op">)</span></span>
<span><span class="va">n_pred</span> <span class="op">&lt;-</span> <span class="fl">3000</span></span>
<span><span class="va">x_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">n_pred</span><span class="op">)</span></span>
<span><span class="va">y_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">n_pred</span><span class="op">)</span></span>
<span><span class="va">sim_preds</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x_pred</span>, y <span class="op">=</span> <span class="va">y_pred</span><span class="op">)</span></span>
<span><span class="va">pred_start_time</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/proc.time.html">proc.time</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">sim_preds</span><span class="op">$</span><span class="va">preds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">bdmod</span>, newdata <span class="op">=</span> <span class="va">sim_preds</span>, local <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">pred_end_time</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/proc.time.html">proc.time</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">pred_end_time</span> <span class="op">-</span> <span class="va">pred_start_time</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">sim_preds</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span>, color <span class="op">=</span> <span class="va">preds</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_color_viridis_c</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">8</span>, <span class="fl">9</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_gray</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span></span>
<span><span class="va">spmods</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>, data <span class="op">=</span> <span class="va">moss</span>,</span>
<span>              spcov_type <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"exponential"</span>, <span class="st">"gaussian"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">spmods</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://usepa.github.io/spmodel/reference/glances.html">glances</a></span><span class="op">(</span><span class="va">spmods</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">spmods</span><span class="op">$</span><span class="va">gaussian</span>, conf.int <span class="op">=</span> <span class="cn">TRUE</span>, conf.level <span class="op">=</span> <span class="fl">0.90</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">spmods</span><span class="op">$</span><span class="va">gaussian</span>, level <span class="op">=</span> <span class="fl">0.90</span><span class="op">)</span></span>
<span><span class="va">moss</span></span>
<span><span class="va">randint</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>                data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>                random <span class="op">=</span> <span class="op">~</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">sample</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">randint</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>                      data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>                      random <span class="op">=</span> <span class="op">~</span> <span class="va">sample</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">randint</span><span class="op">)</span></span>
<span><span class="va">spmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>              data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://usepa.github.io/spmodel/reference/glances.html">glances</a></span><span class="op">(</span><span class="va">spmod</span>, <span class="va">randint</span><span class="op">)</span></span>
<span><span class="va">yearint</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>                      data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>                      random <span class="op">=</span> <span class="op">~</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">sample</span> <span class="op">+</span> <span class="va">year</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">yearsl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>                      data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>                      random <span class="op">=</span> <span class="op">~</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">sample</span><span class="op">)</span> <span class="op">+</span> </span>
<span>                       <span class="op">(</span><span class="va">log_dist2road</span> <span class="op">|</span> <span class="va">year</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://usepa.github.io/spmodel/reference/glances.html">glances</a></span><span class="op">(</span><span class="va">spmod</span>, <span class="va">randint</span>, <span class="va">yearint</span>, <span class="va">yearsl</span><span class="op">)</span></span>
<span><span class="va">nospcov</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>                    data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"none"</span>,</span>
<span>                    random <span class="op">=</span> <span class="op">~</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">sample</span><span class="op">)</span> <span class="op">+</span> </span>
<span>                      <span class="op">(</span><span class="va">log_dist2road</span> <span class="op">|</span> <span class="va">year</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://usepa.github.io/spmodel/reference/glances.html">glances</a></span><span class="op">(</span><span class="va">spmod</span>, <span class="va">randint</span>, <span class="va">yearint</span>, <span class="va">yearsl</span>, <span class="va">nospcov</span><span class="op">)</span></span>
<span><span class="co">## the model with no explicit spatial covariance has the worst fit </span></span>
<span><span class="co">## of the five models.</span></span>
<span><span class="va">aniso</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>              data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>              anisotropy <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">aniso</span></span>
<span><span class="fu"><a href="https://usepa.github.io/spmodel/reference/glances.html">glances</a></span><span class="op">(</span><span class="va">spmod</span>, <span class="va">aniso</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">aniso</span>, which <span class="op">=</span> <span class="fl">8</span><span class="op">)</span></span>
<span><span class="va">part</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>,</span>
<span>             data <span class="op">=</span> <span class="va">moss</span>, spcov_type <span class="op">=</span> <span class="st">"exponential"</span>,</span>
<span>             partition_factor <span class="op">=</span> <span class="op">~</span> <span class="va">year</span><span class="op">)</span></span>
<span><span class="va">init_spher</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spcov_initial.html">spcov_initial</a></span><span class="op">(</span><span class="st">"spherical"</span>, range <span class="op">=</span> <span class="fl">20000</span>, known <span class="op">=</span> <span class="st">"range"</span><span class="op">)</span></span>
<span><span class="va">init_spher</span></span>
<span><span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>, data <span class="op">=</span> <span class="va">moss</span>,</span>
<span>     spcov_initial <span class="op">=</span> <span class="va">init_spher</span><span class="op">)</span></span>
<span><span class="va">init_no_ie</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spcov_initial.html">spcov_initial</a></span><span class="op">(</span><span class="st">"spherical"</span>, ie <span class="op">=</span> <span class="fl">0</span>, known <span class="op">=</span> <span class="st">"ie"</span><span class="op">)</span></span>
<span><span class="va">no_ie</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>, data <span class="op">=</span> <span class="va">moss</span>,</span>
<span>              spcov_initial <span class="op">=</span> <span class="va">init_no_ie</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">no_ie</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">NROW</a></span><span class="op">(</span><span class="va">moss</span><span class="op">)</span></span>
<span><span class="va">n_train</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">0.75</span> <span class="op">*</span> <span class="va">n</span><span class="op">)</span></span>
<span><span class="va">n_test</span> <span class="op">&lt;-</span> <span class="va">n</span> <span class="op">-</span> <span class="va">n_train</span></span>
<span><span class="va">train_index</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">n</span>, size <span class="op">=</span> <span class="va">n_train</span><span class="op">)</span></span>
<span><span class="va">moss_train</span> <span class="op">&lt;-</span> <span class="va">moss</span><span class="op">[</span><span class="va">train_index</span>, , <span class="op">]</span></span>
<span><span class="va">moss_test</span> <span class="op">&lt;-</span> <span class="va">moss</span><span class="op">[</span><span class="op">-</span><span class="va">train_index</span>, , <span class="op">]</span></span>
<span><span class="va">rfsrmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splmRF.html">splmRF</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>, <span class="va">moss_train</span>,</span>
<span>                  spcov_type <span class="op">=</span> <span class="st">"exponential"</span><span class="op">)</span></span>
<span><span class="co"># results omitted</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">rfsrmod</span>, <span class="va">moss_test</span><span class="op">)</span></span>
<span><span class="va">rf_preds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">rfsrmod</span>, newdata <span class="op">=</span> <span class="va">moss_test</span><span class="op">)</span></span>
<span><span class="va">rf_errors</span> <span class="op">&lt;-</span> <span class="va">moss_test</span><span class="op">$</span><span class="va">log_Zn</span> <span class="op">-</span> <span class="va">rf_preds</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">rf_errors</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">splmmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/splm.html">splm</a></span><span class="op">(</span><span class="va">log_Zn</span> <span class="op">~</span> <span class="va">log_dist2road</span>, <span class="va">moss_train</span>,</span>
<span>                  spcov_type <span class="op">=</span> <span class="st">"exponential"</span><span class="op">)</span></span>
<span><span class="va">splm_preds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">splmmod</span>, newdata <span class="op">=</span> <span class="va">moss_test</span><span class="op">)</span></span>
<span><span class="va">splm_errors</span> <span class="op">&lt;-</span> <span class="va">moss_test</span><span class="op">$</span><span class="va">log_Zn</span> <span class="op">-</span> <span class="va">splm_preds</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">splm_errors</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">seal</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="va">log_trend</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_fill_viridis_c</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span> </span>
<span><span class="va">sealmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor</a></span><span class="op">(</span><span class="va">log_trend</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">seal</span>, spcov_type <span class="op">=</span> <span class="st">"car"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">)</span></span>
<span><span class="va">spcov_params_car</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">sealmod</span>, type <span class="op">=</span> <span class="st">"spcov"</span><span class="op">)</span></span>
<span><span class="va">de_car</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/vector.html">as.vector</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">spcov_params_car</span><span class="op">[[</span><span class="st">"de"</span><span class="op">]</span><span class="op">]</span>, digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">range_car</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/vector.html">as.vector</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">spcov_params_car</span><span class="op">[[</span><span class="st">"range"</span><span class="op">]</span><span class="op">]</span>, digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">sealmod</span><span class="op">$</span><span class="va">W</span></span>
<span><span class="va">sealmod</span><span class="op">$</span><span class="va">W</span><span class="op">[</span><span class="fl">1</span>, <span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">$</span><span class="va">W</span><span class="op">[</span><span class="fl">1</span>, <span class="op">]</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/AIC.html">AIC</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">)</span></span>
<span><span class="va">sealmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor</a></span><span class="op">(</span><span class="va">log_trend</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">seal</span>, spcov_type <span class="op">=</span> <span class="st">"car"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">sealmod</span>, newdata <span class="op">=</span> <span class="va">sealmod</span><span class="op">$</span><span class="va">newdata</span><span class="op">)</span></span>
<span><span class="va">is_missing</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">seal</span><span class="op">$</span><span class="va">log_trend</span><span class="op">)</span></span>
<span><span class="va">seal_nomiss</span> <span class="op">&lt;-</span> <span class="va">seal</span><span class="op">[</span><span class="op">!</span><span class="va">is_missing</span>, , <span class="op">]</span></span>
<span><span class="va">sealmod_nomiss</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spautor.html">spautor</a></span><span class="op">(</span><span class="va">log_trend</span> <span class="op">~</span> <span class="fl">1</span>,</span>
<span>                          data <span class="op">=</span> <span class="va">seal_nomiss</span>, spcov_type <span class="op">=</span> <span class="st">"car"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">sealmod</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">sealmod_nomiss</span><span class="op">)</span></span>
<span><span class="va">params</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/spcov_params.html">spcov_params</a></span><span class="op">(</span><span class="st">"exponential"</span>, de <span class="op">=</span> <span class="fl">1</span>, ie <span class="op">=</span> <span class="fl">0.5</span>, range <span class="op">=</span> <span class="fl">5e5</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">sulfate</span><span class="op">$</span><span class="va">z</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/sprnorm.html">sprnorm</a></span><span class="op">(</span><span class="va">params</span>, data <span class="op">=</span> <span class="va">sulfate</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">sulfate</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>color <span class="op">=</span> <span class="va">z</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_color_viridis_c</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_gray</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span></span>
<span><span class="va">esv_out</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://usepa.github.io/spmodel/reference/esv.html">esv</a></span><span class="op">(</span><span class="va">z</span> <span class="op">~</span> <span class="fl">1</span>, <span class="va">sulfate</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">esv_out</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">dist</span>, y <span class="op">=</span> <span class="va">gamma</span>, size <span class="op">=</span> <span class="va">np</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/lims.html">lims</a></span><span class="op">(</span>y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="cn">NA</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_gray</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-bates2015lme4" class="csl-entry" role="doc-biblioentry">
Bates, Douglas, Martin Mächler, Ben Bolker, and Steve Walker. 2015. <span>“Fitting Linear Mixed-Effects Models Using <span class="nocase">lme4</span>.”</span> <em>Journal of Statistical Software</em> 67 (1): 1–48. <a href="https://doi.org/10.18637/jss.v067.i01">https://doi.org/10.18637/jss.v067.i01</a>.
</div>
<div id="ref-pinheiro2006mixed" class="csl-entry" role="doc-biblioentry">
Pinheiro, José, and Douglas Bates. 2006. <em>Mixed-Effects Models in <span>S</span> and <span>S-PLUS</span></em>. Springer science &amp; business media.
</div>
<div id="ref-hoef2023indexing" class="csl-entry" role="doc-biblioentry">
Ver Hoef, Jay M, Michael Dumelle, Matt Higham, Erin E Peterson, and Daniel J Isaak. 2023. <span>“Indexing and Partitioning the Spatial Linear Model for Large Data Sets.”</span> <em>Plos One</em> 18 (11): e0291906.
</div>
<div id="ref-ver2018spatial" class="csl-entry" role="doc-biblioentry">
Ver Hoef, Jay M, Erin E Peterson, Mevin B Hooten, Ephraim M Hanks, and Marie-Josèe Fortin. 2018. <span>“Spatial Autoregressive Models for Statistical Inference from Ecological Data.”</span> <em>Ecological Monographs</em> 88 (1): 36–59.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./splm.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Spatial Linear Models in <code>spmodel</code></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./spglm.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Spatial Generalized Linear Models in <code>spmodel</code></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Workshop materials created by Michael Dumelle and Ryan Hill</div>   
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>